# vim:sw=2:et:

sudo: false
language: erlang
notifications:
  email:
    - alerts@rabbitmq.com
addons:
  apt:
    packages:
      - awscli
      - xsltproc
cache:
  apt: true
env:
  global:
    - secure: T6flNDDRm41HZRSfL/52Z/OJczpuu7JsWv4oapRD6gB7XpM7rOo7zPf7Astms/uJhYqlHW2LpXTr+nf9agzddzFHs9I6dgS/2NjRzDbP0B3pC+S+24zHzfEQSOa+2v0/lws3PI3obOa+3jjcCsIkSu+Y1ftSJMUBvyhYUSP51Y0=
    - secure: QLjIKbB0LXYm9bMyQIanqMffRvSAvr6+IpJ8/ZirZWG9KteMJtO9Eq5YL7SlLF/yoQCFSpLW7//AbLXXm9ga97c0+M7vdqWi/7GN0mrZLCBfO87q/zClmrE/xyCObEiGtBGCQTFxjqrculzW/w+8KSkoApnFeTGkOWw2FmYPmSc=

otp_release:
  - "R16B03-1"
  - "19.3"
  - "20.1"

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, stable branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :

script:
  - make xref
  - make tests

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
